# Docker Compose file for the Hardware Store AI Assistant application.

services:
  # PostgreSQL database service
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ../backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../data/initdb:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ../backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  # Qdrant vector database service
  qdrant:
    image: qdrant/qdrant:v1.9.3
    container_name: hsai-qdrant
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "${QDRANT_PORT:-6333}:6333" # REST + gRPC
    volumes:
      - qdrant_data:/qdrant/storage

  # Redis service for caching
  redis:
    image: redis:7-alpine
    container_name: hsai-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"

  # Backend FastAPI application service
  backend:
    build:
      context: ../backend
    container_name: hsai-backend
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started

# Named volumes for data persistence
volumes:
  db_data:
  qdrant_data:
